# Generated by Django 6.0 on 2026-04-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NRapp', '0005_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='NRapp_produ_categor_abac32_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='NRapp_produ_created_fae26a_idx',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
