# Generated by Django 6.0 on 2026-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NRapp', '0007_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
