# Generated by Django 6.0 on 2026-04-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NRapp', '0008_alter_inquiry_options_inquiry_notes_inquiry_priority_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-created_at']},
        ),
    ]
